---
trust-domain: "{{cookiecutter.trust_domain}}"
task-priority: low

taskgraph:
  cached-task-prefix: "{{cookiecutter.trust_domain}}.v2.{{cookiecutter.project_slug.replace('_', '-')}}"
  repositories:
    {{cookiecutter.project_slug}}:
      name: "{{cookiecutter.repo_name}}"

workers:
  aliases:
    b-linux:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    images:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    t-linux-large:
      provisioner: '{trust-domain}-t'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
