---
version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      deps:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"
