#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -ex

curl -L "https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer" -o /builds/worker/pyenv-installer
chmod +x /builds/worker/pyenv-installer
/builds/worker/pyenv-installer
rm /builds/worker/pyenv-installer
cat << EOF >> /builds/worker/.bashrc
eval "\$(pyenv init --path)"
eval "\$(pyenv init -)"
eval "\$(pyenv virtualenv-init -)"
EOF
source /builds/worker/.bashrc

# Log some debugging info
pyenv --version
git -C "$(pyenv root)" rev-parse HEAD

for i in ${1//,/ }
do
    version=$(pyenv latest --known $i)
    pyenv install $version --verbose
done
chmod 777 /builds/worker/.pyenv/shims
pyenv rehash
